# Generated by Django 3.0.5 on 2020-04-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='choice',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('PHONE', 'Phone'), ('EMAIL', 'Email')], default='Phone', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='courses.Contact', to_field='choice'),
        ),
    ]
